import type { WorkoutType } from "@capgo/capacitor-health";

/** Full list aligned with @capgo/capacitor-health `WorkoutType` (HealthKit / Health Connect). */
export const HEALTHKIT_WORKOUT_TYPE_KEYS = [
  "americanFootball",
  "australianFootball",
  "badminton",
  "baseball",
  "basketball",
  "bowling",
  "boxing",
  "climbing",
  "cricket",
  "crossTraining",
  "curling",
  "cycling",
  "dance",
  "elliptical",
  "fencing",
  "functionalStrengthTraining",
  "golf",
  "gymnastics",
  "handball",
  "hiking",
  "hockey",
  "jumpRope",
  "kickboxing",
  "lacrosse",
  "martialArts",
  "pilates",
  "racquetball",
  "rowing",
  "rugby",
  "running",
  "sailing",
  "skatingSports",
  "skiing",
  "snowboarding",
  "soccer",
  "softball",
  "squash",
  "stairClimbing",
  "strengthTraining",
  "surfing",
  "swimming",
  "swimmingPool",
  "swimmingOpenWater",
  "tableTennis",
  "tennis",
  "trackAndField",
  "traditionalStrengthTraining",
  "volleyball",
  "walking",
  "waterFitness",
  "waterPolo",
  "waterSports",
  "weightlifting",
  "wheelchair",
  "yoga",
  "archery",
  "barre",
  "cooldown",
  "coreTraining",
  "crossCountrySkiing",
  "discSports",
  "downhillSkiing",
  "equestrianSports",
  "fishing",
  "fitnessGaming",
  "flexibility",
  "handCycling",
  "highIntensityIntervalTraining",
  "hunting",
  "mindAndBody",
  "mixedCardio",
  "paddleSports",
  "pickleball",
  "play",
  "preparationAndRecovery",
  "snowSports",
  "stairs",
  "stepTraining",
  "surfingSports",
  "taiChi",
  "transition",
  "underwaterDiving",
  "wheelchairRunPace",
  "wheelchairWalkPace",
  "wrestling",
  "cardioDance",
  "socialDance",
  "backExtension",
  "barbellShoulderPress",
  "benchPress",
  "benchSitUp",
  "bikingStationary",
  "bootCamp",
  "burpee",
  "calisthenics",
  "crunch",
  "dancing",
  "deadlift",
  "dumbbellCurlLeftArm",
  "dumbbellCurlRightArm",
  "dumbbellFrontRaise",
  "dumbbellLateralRaise",
  "dumbbellTricepsExtensionLeftArm",
  "dumbbellTricepsExtensionRightArm",
  "dumbbellTricepsExtensionTwoArm",
  "exerciseClass",
  "forwardTwist",
  "frisbeedisc",
  "guidedBreathing",
  "iceHockey",
  "iceSkating",
  "jumpingJack",
  "latPullDown",
  "lunge",
  "meditation",
  "paddling",
  "paraGliding",
  "plank",
  "rockClimbing",
  "rollerHockey",
  "rowingMachine",
  "runningTreadmill",
  "scubaDiving",
  "skating",
  "snowshoeing",
  "stairClimbingMachine",
  "stretching",
  "upperTwist",
  "other",
] as const satisfies readonly WorkoutType[];

const EMOJI: Partial<Record<WorkoutType, string>> = {
  running: "🏃",
  walking: "🚶",
  cycling: "🚴",
  swimming: "🏊",
  swimmingPool: "🏊",
  swimmingOpenWater: "🏊",
  hiking: "🥾",
  yoga: "🧘",
  pilates: "🤸",
  golf: "⛳",
  pickleball: "🏓",
  tennis: "🎾",
  tableTennis: "🏓",
  basketball: "🏀",
  soccer: "⚽",
  volleyball: "🏐",
  dance: "💃",
  cardioDance: "💃",
  socialDance: "💃",
  dancing: "💃",
  boxing: "🥊",
  kickboxing: "🥊",
  rowing: "🚣",
  rowingMachine: "🚣",
  jumpRope: "🪢",
  elliptical: "🏋️",
  stairClimbing: "🪜",
  stairClimbingMachine: "🪜",
  stairs: "🪜",
  stretching: "🙆",
  flexibility: "🙆",
  martialArts: "🥋",
  traditionalStrengthTraining: "💪",
  strengthTraining: "💪",
  functionalStrengthTraining: "💪",
  weightlifting: "🏋️",
  highIntensityIntervalTraining: "🔥",
  crossTraining: "🔥",
  mixedCardio: "🔥",
  bootCamp: "🔥",
  surfing: "🏄",
  surfingSports: "🏄",
  skiing: "⛷️",
  crossCountrySkiing: "⛷️",
  downhillSkiing: "⛷️",
  snowboarding: "🏂",
  climbing: "🧗",
  rockClimbing: "🧗",
  americanFootball: "🏈",
  baseball: "⚾",
  softball: "🥎",
  iceHockey: "🏒",
  hockey: "🏒",
  rollerHockey: "🏒",
  lacrosse: "🥍",
  rugby: "🏉",
  handball: "🤾",
  gymnastics: "🤸",
  fencing: "🤺",
  archery: "🏹",
  bowling: "🎳",
  sailing: "⛵",
  waterPolo: "🤽",
  meditation: "🧘",
  taiChi: "🧘",
  mindAndBody: "🧘",
  wheelchair: "♿",
  wheelchairRunPace: "♿",
  wheelchairWalkPace: "♿",
  other: "🏋️",
};

export function formatHealthKitWorkoutLabel(key: WorkoutType): string {
  return key
    .replace(/([A-Z])/g, " $1")
    .trim()
    .split(/\s+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(" ");
}

export function emojiForHealthKitWorkoutType(key: WorkoutType): string {
  return EMOJI[key] ?? "🏋️";
}

export interface HealthKitWorkoutOption {
  value: WorkoutType;
  label: string;
  emoji: string;
}

export function getAllHealthKitWorkoutOptions(): HealthKitWorkoutOption[] {
  return HEALTHKIT_WORKOUT_TYPE_KEYS.map((value) => ({
    value,
    label: formatHealthKitWorkoutLabel(value),
    emoji: emojiForHealthKitWorkoutType(value),
  }));
}
